name: hello-world

on: 
    push:
        branches: [ main ]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: run a one-line script
        run: echo "Hello World!"
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with: 
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}


