name: deploy-discord-bot

on:
  push:
    branches: [main]
    
env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd ~/JobSeekerDiscordBot
            git pull
            python3 -m pip install -r requirements.txt
            python3 main.py
